version: "3.2"

networks:
  front-tier:
  back-tier:


services:

  cart:
    image: cartimage
    build: 
      context: .\src\Services\CartApi
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
    container_name: cartapi
    ports:
      - "5500:80"
    networks:
      - back-tier
      - front-tier 
    depends_on:
      - basket.data
      

  basket.data:
    image: redis
    ports:
      - "6377:6379"  
    networks:
      - back-tier 