version: "3.2"

networks:
   front-tier:
   back-tier:

services:
   catalog:
      build:
         context: .\src\Services\ProductCatalogApi
         dockerfile: Dockerfile
      image: ecommerce/catalog
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=MoviesDb
         - DatabaseUser=sa
         - DatabaseUserPassword=Docker@1
      container_name: catalogApi
      ports:
         - "5000:80"
      networks:
         - back-tier
         - front-tier
      depends_on:
         - mssqlserver
         
   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      ports:
         - "1445:1433"

      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Docker@1
      networks:
         - back-tier

      

